version: "3.8"

services:
  db:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build:
      context: ./api
      args:
        WORKDIR: app
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3000:3000"
    volumes:
      - ./api:/$WORKDIR
    depends_on:
      - db

  front:
    build:
      context: ./front
      args:
        WORKDIR: app
        CONTAINER_PORT: 3000
    command: npm run dev
    volumes:
      - ./front:/$WORKDIR
    ports:
      - "8080:3000"
    depends_on:
      - api

volumes:
  mysql-data:
    driver: local
