version: "3.8"

services:
  db:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      # MYSQL_USER: $MYSQL_USER
      # MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql/data

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR 
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "$API_PORT:$CONTAINER_PORT"
    volumes:
      - ./api:/$WORKDIR
    depends_on:
      - db

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
    command: yarn run dev
    volumes:
      - ./front:/$WORKDIR
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    depends_on:
      - api

volumes:
  mysql-data:
    driver: local
