version: "3.8"

services:
  db:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  api:
    build:
      context: ./api
      args:
        WORKDIR: app
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      API_DOMAIN: "localhost:8080"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    depends_on:
      - db

  front:
    build:
      context: ./front
      args:
        WORKDIR: app
        CONTAINER_PORT: 3000
        API_URL: "http://localhost:3000"
    command: npm run dev
    volumes:
      - ./front:/app
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  mysql-data:
    driver: local
